$(document).ready(function(){
  $('body.hidden').fadeIn(1500).removeClass('hidden');
  $("#resume").click(function(){
    $("#myresume").slideToggle("slow");
  });
  $("#project").click(function(){
    $("#myproject").slideToggle("slow");
  });
  $("#contact").click(function(){
    $("#mycontact").slideToggle("slow");
  });
  $("#skills").click(function(){
    $("#myskills").slideToggle("slow");
  });
});